name: Build, Test, Native AOT Compilation & Docker Image CI + Native AOT Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  version:
    name: 🔢 GitVersion
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '6.3.x'

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.2.1

  test:
    name: ✅ Run Tests
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

  native-aot:
    name: 🌐 Native AOT Build (${{ matrix.rid }})
    needs: [test, version]
    strategy:
      matrix:
        rid: [linux-x64, linux-arm64, win-x64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Publish Native AOT for ${{ matrix.rid }}
      run: |
        dotnet publish -c Release -r ${{ matrix.rid }} \
          -p:PublishAot=true \
          -p:Version=${{ needs.version.outputs.version }} \
          -o native-aot/${{ matrix.rid }}

    - name: Upload AOT artifact
      uses: actions/upload-artifact@v4
      with:
        name: native-aot-${{ matrix.rid }}
        path: native-aot/${{ matrix.rid }}

  docker:
    name: 🚢 Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [native-aot, version]
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          dekoeky/http-inspector:${{ needs.version.outputs.version }}
          dekoeky/http-inspector:latest
        platforms: |
          linux/amd64
          linux/arm/v6
          linux/arm/v7
          linux/arm64/v8

    # - name: 📑 Update Docker Hub Description
    #   uses: peter-evans/dockerhub-description@v4
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     repository: dekoeky/http-inspector
    #     short-description: ${{ github.event.repository.description }}
    #     readme-filepath: ./README.md

  release:
    name: 🌟 GitHub Release
    runs-on: ubuntu-latest
    needs: [native-aot, version]
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ needs.version.outputs.version }}
        files: |
          artifacts/native-aot-linux-x64/**
          artifacts/native-aot-linux-arm64/**
          artifacts/native-aot-win-x64/**
